version: '3.8'

services:
  # Backend
  backend:
    container_name: auditoria_examen_3-backend
    build:
      context: ./backend
    ports:
      - "8000:8000"          # Exponemos backend para pruebas y proxy
    volumes:
      - ./backend/vector_store:/app/vector_store
      - ./backend/data:/app/data   # Carpeta donde guardaremos tickets.db
    extra_hosts:
      host.docker.internal: host-gateway

  # Frontend
  frontend:
    container_name: auditoria_examen_3-frontend
    build:
      context: ./frontend
    depends_on:
      - backend

  # Proxy Nginx
  proxy:
    container_name: auditoria_examen_3-proxy
    image: nginx:stable-alpine
    ports:
      - "5173:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
